name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
    - name: Clone Ziglua
      uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.15.0-dev.375+8f8f37fb0

    - name: Run tests
      run: make test
