name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Clone Ziglua
      uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: master

    - name: Run tests
      run: make test

  test_cross:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Clone Ziglua
      uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: master

    - name: Run tests
      run: make test_cross
